URL_SERVICE = "https://5d844e87-92cc-41b5-ad00-31e891d53665.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"